repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9 # Use the latest stable Ruff version
    hooks:
      - id: ruff-check # Runs the linter
        args: [--fix] # Optional: automatically fixes linting issues
      - id: ruff-format # Runs the formatter